//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_ZDARZEN
    {
        public decimal ID_HISTORIA { get; set; }
        public decimal ID_ZAMOWIENIE { get; set; }
        public decimal ID_RODZAJ_ZDARZENIE { get; set; }
        public decimal OPLATA { get; set; }
        public System.DateTime DATA_ZDARZENIE { get; set; }
    
        public virtual RODZAJE_ZDARZEN RODZAJE_ZDARZEN { get; set; }
        public virtual ZAMOWIENIA ZAMOWIENIA { get; set; }
    }
}
