//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKI
    {
        public MARKI()
        {
            this.MODELE = new HashSet<MODELE>();
        }
    
        public decimal ID_MARKA { get; set; }
        public string NAZWA_MARKA { get; set; }
        public string KRAJ { get; set; }
        public string REGION { get; set; }
    
        public virtual ICollection<MODELE> MODELE { get; set; }
    }
}
