//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentalCWBackEntities1 : DbContext
    {
        public CarRentalCWBackEntities1()
            : base("name=CarRentalCWBackEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HISTORIA_ZDARZEN> HISTORIA_ZDARZEN { get; set; }
        public DbSet<KLIENCI> KLIENCI { get; set; }
        public DbSet<KONTA_KLIENTOW> KONTA_KLIENTOW { get; set; }
        public DbSet<KONTA_PRACOWNIKOW> KONTA_PRACOWNIKOW { get; set; }
        public DbSet<MARKI> MARKI { get; set; }
        public DbSet<MODELE> MODELE { get; set; }
        public DbSet<PAKIETY> PAKIETY { get; set; }
        public DbSet<PRACOWNICY> PRACOWNICY { get; set; }
        public DbSet<RODZAJE_NADWOZIA> RODZAJE_NADWOZIA { get; set; }
        public DbSet<RODZAJE_PALIWA> RODZAJE_PALIWA { get; set; }
        public DbSet<RODZAJE_ZDARZEN> RODZAJE_ZDARZEN { get; set; }
        public DbSet<ROLE> ROLE { get; set; }
        public DbSet<SAMOCHODY> SAMOCHODY { get; set; }
        public DbSet<WYPOZYCZALNIE> WYPOZYCZALNIE { get; set; }
        public DbSet<ZAMOWIENIA> ZAMOWIENIA { get; set; }
    }
}
