//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAKIETY
    {
        public PAKIETY()
        {
            this.ZAMOWIENIA = new HashSet<ZAMOWIENIA>();
        }
    
        public decimal ID_PAKIET { get; set; }
        public string NAZWA { get; set; }
        public string ZAWARTOSC { get; set; }
        public decimal CENA { get; set; }
    
        public virtual ICollection<ZAMOWIENIA> ZAMOWIENIA { get; set; }
    }
}
