//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACOWNICY
    {
        public PRACOWNICY()
        {
            this.KONTA_PRACOWNIKOW = new HashSet<KONTA_PRACOWNIKOW>();
            this.ZAMOWIENIA = new HashSet<ZAMOWIENIA>();
        }
    
        public decimal ID_PRAC { get; set; }
        public Nullable<decimal> ID_KON_PRACOWNIK { get; set; }
        public decimal ID_WYPOZYCZALNIA { get; set; }
        public string IMIE_PRACOWNIK { get; set; }
        public string NAZWISKO_PRACOWNIK { get; set; }
        public Nullable<decimal> PESEL_PRACOWNIK { get; set; }
        public string TELEFON_PRACOWNIK { get; set; }
        public string STANOWISKO { get; set; }
        public System.DateTime DATA_ZATRUDNIENIA { get; set; }
        public decimal WYNAGRODZENIE { get; set; }
        public Nullable<decimal> PREMIA { get; set; }
    
        public virtual ICollection<KONTA_PRACOWNIKOW> KONTA_PRACOWNIKOW { get; set; }
        public virtual KONTA_PRACOWNIKOW KONTA_PRACOWNIKOW1 { get; set; }
        public virtual WYPOZYCZALNIE WYPOZYCZALNIE { get; set; }
        public virtual ICollection<ZAMOWIENIA> ZAMOWIENIA { get; set; }
    }
}
