//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RODZAJE_ZDARZEN
    {
        public RODZAJE_ZDARZEN()
        {
            this.HISTORIA_ZDARZEN = new HashSet<HISTORIA_ZDARZEN>();
        }
    
        public decimal ID_RODZAJ_ZDARZENIE { get; set; }
        public string NAZWA_ZDARZENIE { get; set; }
    
        public virtual ICollection<HISTORIA_ZDARZEN> HISTORIA_ZDARZEN { get; set; }
    }
}
