//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RODZAJE_PALIWA
    {
        public RODZAJE_PALIWA()
        {
            this.SAMOCHODY = new HashSet<SAMOCHODY>();
        }
    
        public decimal ID_PALIWO { get; set; }
        public string NAZWA_RODZAJ { get; set; }
    
        public virtual ICollection<SAMOCHODY> SAMOCHODY { get; set; }
    }
}
