//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class WYPOZYCZALNIE
    {
        public WYPOZYCZALNIE()
        {
            this.PRACOWNICY = new HashSet<PRACOWNICY>();
            this.SAMOCHODY = new HashSet<SAMOCHODY>();
            this.ZAMOWIENIA = new HashSet<ZAMOWIENIA>();
        }
    
        public decimal ID_WYPOZYCZALNIA { get; set; }
        public string MIASTO { get; set; }
        public string ADRES { get; set; }
    
        public virtual ICollection<PRACOWNICY> PRACOWNICY { get; set; }
        public virtual ICollection<SAMOCHODY> SAMOCHODY { get; set; }
        public virtual ICollection<ZAMOWIENIA> ZAMOWIENIA { get; set; }
    }
}
