//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAMOWIENIA
    {
        public ZAMOWIENIA()
        {
            this.HISTORIA_ZDARZEN = new HashSet<HISTORIA_ZDARZEN>();
        }
    
        public decimal ID_ZAMOWIENIE { get; set; }
        public Nullable<decimal> ID_PAKIET { get; set; }
        public decimal ID_WYPOZYCZALNIA { get; set; }
        public decimal ID_PRAC { get; set; }
        public decimal ID_KLIENT { get; set; }
        public decimal ID_SAMOCHOD { get; set; }
        public bool SAMOCHOD_WYDANY { get; set; }
        public bool ZREALIZOWANE { get; set; }
        public decimal LICZBA_DNI { get; set; }
        public decimal CENA_ZAMOWIENIE { get; set; }
        public System.DateTime DATA_START { get; set; }
        public System.DateTime DATA_KONIEC { get; set; }
    
        public virtual ICollection<HISTORIA_ZDARZEN> HISTORIA_ZDARZEN { get; set; }
        public virtual KLIENCI KLIENCI { get; set; }
        public virtual PAKIETY PAKIETY { get; set; }
        public virtual PRACOWNICY PRACOWNICY { get; set; }
        public virtual SAMOCHODY SAMOCHODY { get; set; }
        public virtual WYPOZYCZALNIE WYPOZYCZALNIE { get; set; }
    }
}
